### ISSUE TITLE
About Airplay Mirroring

### ISSUE THREAD

**Issue by looksoo** [gpfduoduo/AirPlay-Receiver-on-Android#1]
很高兴看到你的开源工程，请问楼主是否要实现Airplay Mirroring功能？

**Comment by gpfduoduo** [comment]
目前的airplay实现推送图片和视频还是有bug的，后续慢慢研究，airplay mirroring和raop音乐推送好像都经过了加密。而且mirror对android资源的消耗更大，需要不停的解码播放。目前好像有PC版本的可以实现，你可以抓包研究一下。
名字叫：airplayer，大小只有6M左右。我已经试过是 支持mirror的。而且效果不错。
使用方法：在iphone桌面，向上推动，然后点击airplay，会有选项打开mirror（镜像）。iphoto型号为6。
